### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by xDevThomas** [abrander/garmin-connect#1]
Hey ✋🏼,

I'm trying to authenticate the client via:

`./connect authenticate`

unfortunately I get the error:

`social profile not found in HTML`

Is there something I need to do?

Greetings,
Thomas

**Comment by abrander** [comment]
> social profile not found in HTML

This sounds like the bug fixed in b4d24dd. Are you using latest master?

**Comment by xDevThomas** [comment]
Yes, this last commit was missing :/... sorry. Now it works like a charm!
