### ISSUE TITLE
Upload problem (bodycomposition)

### ISSUE THREAD

**Issue by RobertWojtowicz** [abrander/garmin-connect#17]
Hi, @abrander

Could you please check if your client is working properly with Garmin API ?
I'm having a connection problem (bodycomposition uses this client) , looks like Garmin changed something:
https://github.com/davidkroell/bodycomposition/issues/14
https://github.com/petergardfjall/garminexport/issues/84

Best Regards
Robert

**Comment by abrander** [comment]
This could be the issue fixed in #16. Have you tried newest master?

**Comment by RobertWojtowicz** [comment]
thank you, it works :)
