### ISSUE TITLE
Upload problem with activities

### ISSUE THREAD

**Issue by derIckeBrln** [abrander/garmin-connect#18]
By uploading a tcx-file (that worked that way in the past) with the following command:
./connect -s $AUTHFILE activities import data/newrun.tcx

I get now the following error:
invalid character 'w' looking for beginning of value

Uploading the same file(s) via webui (https://connect.garmin.com/modern/import-data) to ensure theres no corruption in the format works

**Comment by RobertWojtowicz** [comment]
Use new version:
https://github.com/abrander/garmin-connect/issues/17#issuecomment-1002265395

**Comment by derIckeBrln** [comment]
Hi Robert,

thanks for the quick response.
I already tried pulling it with the docomented "go get github.com/abrander/garmin-connect/connect" but had no success with that.

**Comment by abrander** [comment]
Cool, you got it solved :slightly_smiling_face: 

It would be nice to make `connect` somewhat nicer, including a `version` command.

For me `connect` is just a small test case for the library itself. If someone would like to add something like a version command or fix the documentation, I would love a PR. I'll close this as the current issue is solved.

(`debug/buildinfo` in Go 1.18+ could make this easy. I think.)

**Comment by derIckeBrln** [comment]
And its a really impressive test case, thanks for your great work.

I will have to dig a bit deeper into go, but I'll put it on my list to create PRs for this.
