### ISSUE TITLE
Unknown revision v0.0.0 on latest go1.17.6

### ISSUE THREAD

**Issue by JoooostB** [abrander/garmin-connect#19]
Hi,

When installing on latest Go version `1.17.6` the following error occurs:
```bash
go get github.com/abrander/garmin-connect/connect
go get: github.com/abrander/garmin-connect/connect@v0.0.0-20211222095001-064d09050879 requires
        github.com/abrander/garmin-connect@v0.0.0: reading github.com/abrander/garmin-connect/go.mod at revision v0.0.0: unknown revision v0.0.0
```

Looks like it is related to changes to Go after 1.15, as both 1.16 and 1.17 seem to be having trouble installing the package.

**Comment by abrander** [comment]
Oh this is so broken. The reasoning for there being two go.mod's is to avoid other applications using the package having a dependency on Cobra.

I think we should go back to the days before 064d09050879ca1172b1265b2b285f4e9a3b0885 and simply update the client go.mod all-the-freaking-time. Sigh.

**Comment by abrander** [comment]
Well. At least we're not alone: https://github.com/golang/go/issues/44840.

**Comment by keslerm** [comment]
Might be worth just splitting off the CLI into it's own repo.

I'd assume most people pulling this in are looking at using as a library.
